# Generated by Django 3.2.7 on 2021-09-29 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('birthDate', models.DateField()),
                ('address', models.CharField(max_length=50)),
                ('phoneNumber', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.DateField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('type', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250)),
                ('artistID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artcraft.artist')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=20)),
                ('address', models.CharField(max_length=50)),
                ('phoneNumber', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderPrice', models.IntegerField()),
                ('orderDate', models.DateField(max_length=20)),
                ('artworkID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artcraft.artwork')),
                ('customerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artcraft.customer')),
            ],
        ),
    ]
