# Generated by Django 3.2.7 on 2021-09-29 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artcraft', '0002_auto_20210929_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterModelTable(
            name='artist',
            table='Artist',
        ),
        migrations.AlterModelTable(
            name='artwork',
            table='Artwork',
        ),
        migrations.AlterModelTable(
            name='customer',
            table='Customer',
        ),
        migrations.AlterModelTable(
            name='order',
            table='Order',
        ),
    ]
